### ISSUE TITLE
自动创建账号

### ISSUE THREAD

**Issue by peng-hui** [rrrrat/hzm-bus#2]
可以使用tmpmail之类的临时邮件工具创建海量账号

Ref: 
https://github.com/sdushantha/tmpmail
https://github.com/sameera-madushan/Mail-Swipe

**Comment by rrrrat** [comment]
这个我们有简易的临时邮箱创建工具，单线程1小时大概可以生成2000个邮箱账号

**Comment by peng-hui** [comment]
是的，我模仿你的代码用临时邮箱自动创建了HZM-BUS账号😄我没有用DB直接把账号存在了文件里。虽然没抢到票（

感谢！
